### PR TITLE
Allow Symfony 4 filesystem components. Unblocks composer install on Drupal >= 8.9.0

### PR DESCRIPTION
**Pull request by homotechsual**
Allow Symfony 4 filesystem components for installation on Drupal 8.9.*/9.*.* via Composer.

### CODE REVIEW

**Comment by MikeyMJCO** [comment]
Some test failures when running against a D8 site. Not sure if `cv` + d8 failures or patch-change failures.

**Comment by MikeyMJCO** [comment]
```
PHPUnit 5.7.27 by Sebastian Bergmann and contributors.

..........................E.....F....E................F...F...FF. 65 / 94 ( 69%)
.............................                                     94 / 94 (100%)

Time: 2.36 minutes, Memory: 6.00MB

There were 2 errors:

1) Civi\Cv\Command\DebugContainerCommandTest::testShowAll
Civi\Cv\Exception\ProcessErrorException: Process failed:
[[ COMMAND: /home/mikey/cv/bin/cv debug:container ]]
[[ CWD: /var/www/drupal8/web ]]
[[ EXIT CODE: 1 ]]
[[ STDOUT ]]

[[ STDERR ]]
The debug command ignores the container cache.


  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Call to undefined method Symfony\Component\DependencyInjection\Definition::getFactoryClass()


debug:container [--out OUT] [--level LEVEL] [-t|--test] [-U|--user USER] [--] [<path>]




/home/mikey/cv/src/Util/Process.php:65
/home/mikey/cv/tests/Command/DebugContainerCommandTest.php:16

2) Civi\Cv\Command\EvalCommandTest::testBootLevels with data set #4 ('cms-full')
Civi\Cv\Exception\ProcessErrorException: Process failed:
[[ COMMAND: /home/mikey/cv/bin/cv ev 'echo "Hello world";' --level=cms-full ]]
[[ CWD: /var/www/drupal8/web ]]
[[ EXIT CODE: 1 ]]
[[ STDOUT ]]

[[ STDERR ]]


  [Exception]
  This system does not appear to have CiviCRM


php:eval [--out OUT] [--level LEVEL] [-t|--test] [-U|--user USER] [--] [<code>]




/home/mikey/cv/src/Util/Process.php:65
/home/mikey/cv/tests/Command/EvalCommandTest.php:52

--

There were 5 failures:

1) Civi\Cv\Command\EvalCommandTest::testBoot
Failed asserting that 'not-found
' matches PCRE pattern "/^found$/".

/home/mikey/cv/tests/Command/EvalCommandTest.php:32

2) Civi\Cv\Command\PathCommandTest::testConfigPaths
Check templateCompileDir/en_US
Failed asserting that false is true.

/home/mikey/cv/tests/Command/PathCommandTest.php:90

3) Civi\Cv\Command\ShowCommandTest::testShowJson
Failed asserting that 'Unknown' matches PCRE pattern "/^([0-9\.\-]|alpha|beta|master|x)+$/".

/home/mikey/cv/tests/Command/ShowCommandTest.php:18

4) Civi\Cv\Command\UrlCommandTest::testExtPaths
Failed asserting that 'http://172.18.32.1/libraries/civicrm/core' matches PCRE pattern ";https?://.*/civicrm$;".

/home/mikey/cv/tests/Command/UrlCommandTest.php:59

5) Civi\Cv\Command\UrlCommandTest::testDynamicExprPaths
Failed asserting that 'http://172.18.32.1/libraries/civicrm/core' matches PCRE pattern ";https?://.*/civicrm$;".

/home/mikey/cv/tests/Command/UrlCommandTest.php:75

ERRORS!
Tests: 94, Assertions: 215, Errors: 2, Failures: 5.
```

**Comment by seamuslee001** [comment]
@totten

**Comment by altsalt** [comment]
@totten just wanted to give a bit of a nudge here as we continue to work on migrating our site to d9. Thanks for maintaining this!

**Comment by totten** [comment]
* OK, the patch list looks long... but I did local-only rebase, and it appears that the only unmerged change is https://github.com/civicrm/cv/pull/76/commits/21bd5418cf278c74daf39b36659059d5556748f5. 
* The test results on my local D7+WP appear the same with or without the patch; so that's good. No regression.  👍 
* My recollection is that the sticking-point was `symfony/console`. (A quick local trial run still shows that updating `symfony/console` causes problems for `ExtensionLifecycleTest` on D7+Civi 5.44.) The current branch only updates `symfony/filesystem`, so that explains why it's safe.
* But then... is that really enough to allow composer-based install on? Aren't all of the Symfony components (filesystem+console+process) common in D8+ deployments? Don't you need to solve that to address your real goal?
* Is there any reason to keep v2 and v3 support on the books? It's much easier on the brain to have fewer versions to support - and the other platforms (D7/WP/BD/J) are phar-only + php-scoper. If the tests are passing with a newer version, shouldn't we just upgrade generally?

**Comment by homotechsual** [comment]
Superceded by #103

**Pull request closed without merging**
