### PR TITLE
New cv upgrade command

### PR DESCRIPTION
**Pull request by agh1**
Mainly in prep for https://issues.civicrm.org/jira/browse/CRM-19417

### CODE REVIEW

**Comment by totten** [comment]
@agh1 I've added a few small fixes. (Described in commit notes.)

One blocker issue in `UpgradeCommand` -- the calls to subprocesses pass through data without proper escaping. I suspect they work in typical usage but would break in some scenarios, like if:
 * The `$problem` report includes any single-quotes.
 * The `$dl['url']` includes any shell characters (eg '&' is common in URLs)
 * The user passes in a `$reportName`  or `$stability` with a shell characters.
 * The `sys_get_temp_dir()` has spaces. (Most Linux systems just use `/tmp` which is fine, but Win/OSX do funny things.)

Suggestion: all variables passed through to `Cv::run()` should be escaped with `escapeshellarg()`.

**Comment by seanmadsen** [comment]
When this is merged, it'd be nice to add an answer to this [SE question](https://civicrm.stackexchange.com/questions/18563/how-do-i-use-cv-to-run-database-upgrades-from-the-command-line) which mentions the new command.

**Comment by totten** [comment]
@agh1 I've made a few updates on this PR

1. *Rebased to match latest `master`* (and force-pushed `agh1:cv-upgrade`)
2. *Significantly revamped the `upgrade:db` command* to support more detailed output. If executed interactively with the default `--out=pretty`, it will display a lot more info. With `-v` or `-vv`, it'll display still more. With `-q`, it'll be quiet. If executed with a structured format (e.g. `--out=json`), it should still return the same content.
3. *Temporarily disabled the other sub-commands.* I think it would be useful to get *something* merged, and we've set the bar rather high by putting all the commands together. I think it'd be an improvement to get this merged with at least one command. (If nothing else, it'll be easier to maintain the code for all the commands... because they'll show up during grep+refactor cycles.)

**Comment by totten** [comment]
I did a local build with #2 and #35 and ran the full `cv` test suite on D7/WordPress/Backdrop, and there don't appear to be any regressions here. 

Let's get this merged already!

**Comment by totten** [comment]
@seanmadsen Posted a comment on https://civicrm.stackexchange.com/a/22949/93 about the `cv upgrade:db` command.

**Pull request merged**
