### PR TITLE
Update to use Symfony Console v4

### PR DESCRIPTION
**Pull request by seamuslee001**
This applies Tim's trick from #71 to fix issue with exit codes and updates Symfony Console version to be 4.x so that we can install on d9 using composer.

### CODE REVIEW

**Comment by seamuslee001** [comment]
@totten @homotechsual I have tested locally and this works on bmaster and wp-demo builds fine

**Comment by totten** [comment]
@seamuslee001 There was a merge-conflict after merging the contemporaneous #104, so I resolved the MC. Also pushed up a change to more strictly use Symfony Console v4. If you're good with these, then we can merge.

**Comment by totten** [comment]
Note: I did retest this on wpmaster@5.39 and dmaster@5.46.alpha - both worked well. ✅

**Comment by seamuslee001** [comment]
I have no issues with the updates @totten

**Comment by totten** [comment]
Tagged v0.3.14. Build at https://test.civicrm.org/view/Tools/job/Tool-Publish-cv/119/

**Pull request merged**
